version: "3.0"

expectations:
  population_size: 1000

actions:
  generate_dataset:
    run: ehrql:v1 generate-dataset --output output/dataset.csv analysis/dataset_definition.py
    outputs:
      highly_sensitive:
        dataset: output/dataset.csv

  do_analysis:
   run: python:latest python analysis/analyse.py
   needs: [generate_dataset]
   outputs:
    moderately_sensitive:
      dataset: output/final_data.csv